# Generated by Django 3.2.17 on 2023-02-08 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20230208_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
